In [4]:
import numpy as np


In [9]:
# 1.Creating a numpy array


In [14]:
#array from a python list
a=[2,4,6,8,10]
b=np.array(list1)

In [15]:
b

array([ 2,  4,  6,  8, 10])

In [29]:
a

[2, 4, 6, 8, 10]

In [17]:
type(a)

list

In [19]:
type(b)

numpy.ndarray

In [20]:
list1=a
arr1=b

In [21]:
 list1+1

TypeError: can only concatenate list (not "int") to list

In [22]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [25]:
list2=[[9,0,4,6],
      [4,6,2,1]]
arr2=np.array(list2)

In [26]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [27]:
#float array
arr2=np.array(list2,dtype='float')


In [28]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [30]:
arr3=arr2.astype('int')

In [31]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [34]:
arr4=np.array(list2,dtype='bool')

In [35]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
list2

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [38]:
 arr5=np.array([2,3,2.0,'y'],dtype='object' )

In [39]:
arr5

array([2, 3, 2.0, 'y'], dtype=object)

In [40]:
#to convert arr to list
list3=arr5.tolist()

In [41]:
list3

[2, 3, 2.0, 'y']

In [42]:
type(list3)

list