In [9]:
import numpy as np


In [10]:
# 1.Creating a numpy array


In [36]:
#array from a python list
a=[2,4,6,8,10]
b=np.array(a)

In [37]:
b

array([ 2,  4,  6,  8, 10])

In [38]:
a

[2, 4, 6, 8, 10]

In [39]:
type(a)

list

In [40]:
type(b)

numpy.ndarray

In [42]:
list1=a
arr1=b

In [76]:
 list1+1

TypeError: can only concatenate list (not "int") to list

In [77]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [78]:
list2=[[9,0,4,6],
      [4,6,2,1]]
arr2=np.array(list2)

In [79]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [80]:
#float array
arr2=np.array(list2,dtype='float')


In [81]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [82]:
arr3=arr2.astype('int')

In [83]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [84]:
arr4=np.array(list2,dtype='bool')

In [85]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
list2

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [87]:
 arr5=np.array([2,3,2.0,'y'],dtype='object' )

In [88]:
arr5

array([2, 3, 2.0, 'y'], dtype=object)

In [89]:
#to convert arr to list
list3=arr5.tolist()

In [90]:
list3

[2, 3, 2.0, 'y']

In [91]:
type(list3)

list

In [92]:

a

[2, 4, 6, 8, 10]

In [93]:
#L2 ARRAY DIMENSION

In [94]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [95]:
#shape of array
arr2.shape

(2, 4)

In [96]:
#no. of elements
arr2.size

8

In [97]:
#type
arr2.dtype

dtype('float64')

In [98]:
 arr2.ndim

2

In [99]:
#L3 REVERSING ROWS AND COLUMNS

In [100]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [101]:
#reverse rows
arr2[::-1]

array([[4., 6., 2., 1.],
       [9., 0., 4., 6.]])

In [102]:
arr2[::-1,::-1]

array([[1., 2., 6., 4.],
       [6., 4., 0., 9.]])

In [103]:
#L4 SPECIFIC ELEMENT EXTRACTION

In [104]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [105]:
arr2[0,:]

array([9., 0., 4., 6.])

In [106]:
arr2[:1,:]

array([[9., 0., 4., 6.]])

In [107]:
arr2[:2,:]

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [108]:
arr2[:-1,:]

array([[9., 0., 4., 6.]])

In [109]:
#last column
arr2[:,:3]

array([[9., 0., 4.],
       [4., 6., 2.]])

In [110]:
 arr2[:,:-1]

array([[9., 0., 4.],
       [4., 6., 2.]])

In [111]:
arr2[:1,:3] #1,2

array([[9., 0., 4.]])

In [ ]:
#l5 BASIC STATISTICS

In [112]:
 arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [113]:
arr2.min()

0.0

In [114]:
arr2.max()

9.0

In [115]:
arr2.sum()

32.0

In [116]:
arr2.mean()

4.0

In [118]:
np.median(arr2)

4.0

In [120]:
np.average(arr2)

4.0

In [121]:
#variance
np.var(arr2)

7.75

In [ ]:
#l-6 RESHAPING AND FLATENNING

In [122]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [123]:
arr2.shape

(2, 4)

In [126]:
arr2.reshape(4,2)

array([[9., 0.],
       [4., 6.],
       [4., 6.],
       [2., 1.]])

In [127]:
arr2.reshape(1,8)

array([[9., 0., 4., 6., 4., 6., 2., 1.]])

In [128]:
arr2.reshape(8,1)

array([[9.],
       [0.],
       [4.],
       [6.],
       [4.],
       [6.],
       [2.],
       [1.]])

In [129]:
arr2.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [131]:
#single dimension
f1=arr2.flatten()

In [132]:
f1

array([9., 0., 4., 6., 4., 6., 2., 1.])

In [133]:
f1.ndim

1

In [ ]:
#L7 RANDOM ARRAYS AND SEQUENCES

In [135]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [138]:
np.arange(10,0)

array([], dtype=int32)

In [139]:
#starting from 10 not 0 in descending order

np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [141]:
#mention start,stop,total no of elements
#equal spaces

np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [142]:
np.linspace(1,10,3)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [143]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [145]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#l-8 UNIQUE ITEMS AND COUNT

In [155]:
arr=[[1,4,5,2,2,5],
[4,4,1,7,4,5]]

In [156]:
arr

[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [157]:
u_val, count= np.unique(arr, return_counts=True)

In [158]:
u_val

array([1, 2, 4, 5, 7])

In [159]:
  count

array([2, 2, 4, 3, 1], dtype=int64)