# L-1-2 LOGISTIC REGRESSION

## IMPORTING LIBRARY

In [27]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.axes as ax

#about data
1. area A
2.perimeter P
3.compactness C= 4.piA/p^2
4.length of kernel
5.width of kernel
6.asymmetry coffecient
7.length of kernel groove

In [28]:
import pandas as pd

# Loading data from CSV file
data = pd.read_csv('C:/Users/kriti/Downloads/seeds (1).csv')


In [30]:
#a little bit of exploration
data.head(10)

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   
5  14.38      14.21       0.8951          5.386         3.312   
6  14.69      14.49       0.8799          5.563         3.259   
7  16.63      15.46       0.8747          6.053         3.465   
8  16.44      15.25       0.8880          5.884         3.505   
9  15.26      14.85       0.8696          5.714         3.242   

   Asymmetry.Coeff  Kernel.Groove  Type  
0            2.221          5.220     1  
1            1.018          4.956     1  
2            2.699          4.825     1  
3            2.259          4.805     1  
4            1.355          5.175     1  
5            2.462          4.956     1  
6            3.586          5.219     1  
7            2.040          5.877     1  
8            1.969          5.533     1  
9            4.543          5.314     1

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Area             199 non-null    float64
 1   Perimeter        199 non-null    float64
 2   Compactness      199 non-null    float64
 3   Kernel.Length    199 non-null    float64
 4   Kernel.Width     199 non-null    float64
 5   Asymmetry.Coeff  199 non-null    float64
 6   Kernel.Groove    199 non-null    float64
 7   Type             199 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 12.6 KB


In [32]:
#counting unique values


In [38]:
data['Type'].unique()

array([1, 2, 3], dtype=int64)

In [39]:
data['Type'].value_counts()

2    68
1    66
3    65
Name: Type, dtype: int64

In [40]:
#splitting data

In [41]:
x=data.drop(data.columns[[7]],axis=1)
y=data['Type'] 
#INPUT AND OUTPUT

In [42]:
x.head()

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry.Coeff  Kernel.Groove  
0            2.221          5.220  
1            1.018          4.956  
2            2.699          4.825  
3            2.259          4.805  
4            1.355          5.175

In [46]:
from sklearn.model_selection import train_test_split

# Assuming you have your data in 'x' (features) and 'y' (labels) arrays
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.02, random_state=0)


In [47]:
#feature scaling

In [49]:
from sklearn.preprocessing import StandardScaler 
sc_x = StandardScaler()

# Fit and transform the training data
x_train = sc_x.fit_transform(x_train)

# Transform the test data using the scaler fitted on the training data
x_test = sc_x.transform(x_test)


In [50]:
x_train

array([[-1.15519945, -0.98520463, -2.18072206, ..., -1.5475717 ,
         0.25429409, -0.4832457 ],
       [-1.04805272, -1.20878231,  0.36782842, ..., -0.82809188,
        -0.06122993, -0.58544838],
       [-0.18050988, -0.29134287,  1.0337813 , ...,  0.12854979,
        -0.83137996, -0.9452018 ],
       ...,
       [ 0.43817605,  0.61067743, -0.51583984, ...,  0.3284053 ,
         0.40628846,  0.58170619],
       [-0.01460528,  0.06329759, -0.14017411, ..., -0.01534617,
        -1.05733588, -0.13780066],
       [-0.84412831, -0.90810888, -0.01210624, ..., -0.65754852,
         0.88194941, -0.55478758]])

In [51]:
#Logistic Regression

TRAINING MODEL

In [53]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [54]:
#predcting Test_input

In [55]:
y_pred=classifier.predict(x_test)

In [56]:
#results

In [58]:
from sklearn.metrics import confusion_matrix


cm = confusion_matrix(y_test, y_pred)


In [59]:
cm

array([[0, 0, 1],
       [0, 2, 0],
       [0, 0, 1]], dtype=int64)

In [61]:
#accuracy sum up values in matrix/number of values in matrix
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.75

# L 3-4 K-NN (k nearest neighbours)

In [62]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.axes as ax

In [63]:

# Loading data from CSV file
data = pd.read_csv('C:/Users/kriti/Downloads/seeds (1).csv')


In [64]:
#a little bit of exploration
data.head(10)

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   
5  14.38      14.21       0.8951          5.386         3.312   
6  14.69      14.49       0.8799          5.563         3.259   
7  16.63      15.46       0.8747          6.053         3.465   
8  16.44      15.25       0.8880          5.884         3.505   
9  15.26      14.85       0.8696          5.714         3.242   

   Asymmetry.Coeff  Kernel.Groove  Type  
0            2.221          5.220     1  
1            1.018          4.956     1  
2            2.699          4.825     1  
3            2.259          4.805     1  
4            1.355          5.175     1  
5            2.462          4.956     1  
6            3.586          5.219     1  
7            2.040          5.877     1  
8            1.969          5.533     1  
9            4.543          5.314     1

In [65]:
#counting unique values
data['Type'].unique()

array([1, 2, 3], dtype=int64)

In [66]:
data['Type'].value_counts()

2    68
1    66
3    65
Name: Type, dtype: int64

In [67]:
#splitting data
x=data.drop(data.columns[[7]],axis=1)
y=data['Type'] 
#INPUT AND OUTPUT

In [68]:
x.head()

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry.Coeff  Kernel.Groove  
0            2.221          5.220  
1            1.018          4.956  
2            2.699          4.825  
3            2.259          4.805  
4            1.355          5.175

In [69]:
#feature scaling
from sklearn.preprocessing import StandardScaler 
sc_x = StandardScaler()

# Fit and transform the training data
x_train = sc_x.fit_transform(x_train)

# Transform the test data using the scaler fitted on the training data
x_test = sc_x.transform(x_test)


In [70]:
#K NEAREST NEIGHBOUR
#TRAININ MODEL

In [74]:
from sklearn.neighbors import KNeighborsClassifier

# Assuming you have already defined x_train and y_train
knn_classifier = KNeighborsClassifier(n_neighbors=3, p=2)
# The 'metric' parameter is set to 'minkowski' for the Euclidean distance (p=2).
# If p=1, it represents the Manhattan distance.

knn_classifier.fit(x_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [76]:
#predicting Test_input
y_pred=knn_classifier.predict(x_test)

In [77]:
#results

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score


cm = confusion_matrix(y_test, y_pred)
  

In [79]:
accuracy_score(y_test, y_pred)

0.75